---

version: "3"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    depends_on:
      - redis
    ports:
      - "8081:3000"

  redis:
    image: redis:7
    volumes:
      - redis-data:/data

volumes:
  redis-data:
